version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: inwork-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inwork
    ports:
      - '5434:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
